package ui;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.io.IOException;
import java.net.URL;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ResourceBundle;

import javax.swing.JOptionPane;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.PasswordField;
import service.dao.CivilDao;
import service.dao.UserDao;

public class CgtmdpController implements Initializable{
	@FXML
	private TextField lblutico;
	@FXML
	private PasswordField mdpact;
	@FXML
	private PasswordField nvmdp;
	@FXML
	private Button btn_vali;
	@FXML
	private Button btn_annu;
	@FXML
	private Label lbl_faux;

	// Event Listener on PasswordField[#mdpact].onAction
	@FXML
	public void testmdp(ActionEvent event) {
		// TODO Autogenerated
		int iduti=0;
		CivilDao civ = new CivilDao();
		UserDao user = new UserDao();
		iduti=civ.getIdco();
		Connection connection = user.getConnection();
		Statement statement=null;
		try {
			statement = connection.createStatement();
			String query = "select * from civil where IdCiv="+iduti+" AND motDePasse='"+mdpact.getText()+"'";
			ResultSet result =statement.executeQuery(query);
			if(result.next()) {
			}else {
				lbl_faux.setVisible(true);
			}
		} catch (SQLException f) {
			throw new RuntimeException(f);
		}
	}
	
	@FXML
	public void btnvalmdp(ActionEvent e) {
		int iduti=0;
		CivilDao civ = new CivilDao();
		UserDao user = new UserDao();
		iduti=civ.getIdco();
		Connection connection = user.getConnection();
		Statement statement=null;
		if(mdpact.getText().length()==0 || nvmdp.getText().length()==0) {
			JOptionPane.showMessageDialog(null, "Veuillez remplir les champs svp", "Erreur", JOptionPane.ERROR_MESSAGE);
		}else {
			try {
				statement = connection.createStatement();
				String query = "select * from civil where IdCiv="+iduti+" AND motDePasse='"+mdpact.getText()+"'";
				ResultSet result =statement.executeQuery(query);
				if(result.next()) {
					query="UPDATE civil SET motDePasse='"+nvmdp.getText()+"' WHERE IdCiv="+iduti;
					statement.executeQuery(query);
					JOptionPane.showMessageDialog(null, "Mot de passe changé", "Réussite", JOptionPane.INFORMATION_MESSAGE);
					try {
						Parent page =(Parent) FXMLLoader.load(getClass().getResource("Menu.fxml"));
						Scene scene4 = new Scene(page);
						Main.window.setScene(scene4);
						Main.window.setTitle("Menu");
						Main.window.setWidth(600);
						Main.window.setHeight(300);
					} catch (IOException g) {
						// TODO Auto-generated catch block
						g.printStackTrace();
					}
				}else {
					lbl_faux.setVisible(true);
				}
			} catch (SQLException f) {
				throw new RuntimeException(f);
			}
		}
	}
	@FXML
	public void btnannmdp(ActionEvent e) {
		try {
			Parent page =(Parent) FXMLLoader.load(getClass().getResource("Menu.fxml"));
			Scene scene4 = new Scene(page);
			Main.window.setScene(scene4);
			Main.window.setTitle("Menu");
			Main.window.setWidth(600);
			Main.window.setHeight(340);
		} catch (IOException g) {
			// TODO Auto-generated catch block
			g.printStackTrace();
		}
	}

	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		int iduti=0;
		CivilDao civ = new CivilDao();
		UserDao user = new UserDao();
		iduti=civ.getIdco();
		Connection connection = user.getConnection();
		Statement statement=null;
		try {
			statement = connection.createStatement();
			String query = "select * from civil where IdCiv="+iduti;
			ResultSet result =statement.executeQuery(query);
			while(result.next()) {
				lblutico.setText(result.getString("Login"));
			}
		} catch (SQLException f) {
			throw new RuntimeException(f);
		}
	}
}
