package ui;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import service.dao.*;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import organisation.Organisation;

import java.io.IOException;
import java.net.URL;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.Instant;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ResourceBundle;

import javax.swing.JOptionPane;

import javafx.event.ActionEvent;

public class FichOrgController implements Initializable{
	@FXML
	private TextField nom;
	@FXML
	private TextField siesoc;
	@FXML
	private TextField dir;
	@FXML
	private TextField membres;
	@FXML
	private TextField comm;
	@FXML
	private TextField idorg;
	@FXML
	private Button btnval;
	@FXML
	private Button btnann;
	private Organisation org;
	
	public FichOrgController(Organisation org) {
		this.org=org;
	}
	
	// Event Listener on Button[#btnval].onAction
	@FXML
	public void btnvalh(ActionEvent event) {
		// TODO Autogenerated
		if (membres.getText().length()==0 || dir.getText().length()==0 || siesoc.getText().length()==0 || nom.getText().length()==0) {
			JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs terminant par * svp", "Erreur", JOptionPane.ERROR_MESSAGE);
		}else {
			if (idorg.getText().length()!=0) {
				UserDao user = new UserDao();
				Connection conn = user.getConnection();
				Statement statement=null;
				
				try {
					statement = conn.createStatement();
					String query = "UPDATE organisation SET nom = '"+nom.getText()+"', siegeSocial= '"+siesoc.getText()+"', dirigeant= '"+dir.getText()+"', membres= '"+membres.getText()+"'";
					if (comm.getLength()!=0) {
						query+=", commentaire= '"+comm.getText()+"'";
					}
					query+=" WHERE idOrg = '"+idorg.getText()+"'";
					statement.executeQuery(query);
					JOptionPane.showMessageDialog(null, "Modification réussie", "Information", JOptionPane.INFORMATION_MESSAGE);
					try {
						Parent page =(Parent) FXMLLoader.load(getClass().getResource("Organisation.fxml"));
						Scene scene4 = new Scene(page);
						Main.window.setScene(scene4);
					} catch (IOException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
					Main.window.setTitle("Organisations");
					Main.window.setWidth(910);
					Main.window.setHeight(680);
				} catch (SQLException e) {
					throw new RuntimeException(e);
				}
			}else {
				UserDao user = new UserDao();
				Connection conn = user.getConnection();
				DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd").withZone( ZoneId.systemDefault() );
				Statement statement=null;
				
				try {
					statement = conn.createStatement();
					String query = "INSERT INTO organisation (nom, siegeSocial, dirigeant, membres, dateAjout";
					if (comm.getText().length()!=0) {
						query+=",commentaire";
					}
					query+=") VALUES ('"+nom.getText()+"','"+siesoc.getText()+"','"+dir.getText()+"','"+membres.getText()+"','"+formatter.format(Instant.now())+"'";
					if (comm.getText().length()!=0) {
						query+=",'"+comm.getText()+"'";
					}
					query+=")";
					statement.executeQuery(query);
					JOptionPane.showMessageDialog(null, "Enregistrement réussi", "Information", JOptionPane.INFORMATION_MESSAGE);
					try {
						Parent page =(Parent) FXMLLoader.load(getClass().getResource("Organisation.fxml"));
						Scene scene4 = new Scene(page);
						Main.window.setScene(scene4);
					} catch (IOException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
					Main.window.setTitle("Organisations");
					Main.window.setWidth(910);
					Main.window.setHeight(680);
				} catch (SQLException e) {
					throw new RuntimeException(e);
				}
			}
		}
	}
	// Event Listener on Button[#btnann].onAction
	@FXML
	public void btnannh(ActionEvent event) {
		// TODO Autogenerated
		try {
			Parent page =(Parent) FXMLLoader.load(getClass().getResource("Organisation.fxml"));
			Scene scene4 = new Scene(page);
			Main.window.setScene(scene4);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		Main.window.setTitle("Organisations");
		Main.window.setWidth(910);
		Main.window.setHeight(680);
	}
	public void remplissage(Organisation org) {
		//SSuSystem.out.println(org.getId());
	}
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		if (org!=null) {
			nom.setText(org.getNom());
			membres.setText(Integer.toString(org.getMembres()));
			idorg.setText(Integer.toString(org.getId()));
			String str = org.getCommentaire();
			if(str!=null) {
				comm.setText(str);
			}
			dir.setText(org.getDirigeant());
			siesoc.setText(org.getSiegeSocial());
		}
		System.out.println(idorg.getText());
	}
}
