package ui;

import java.io.IOException;
import java.net.URL;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.ZoneOffset;
import java.util.ArrayList;
import java.util.ResourceBundle;

import javax.swing.JOptionPane;

import controller.UserController;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Slider;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TableView;
import javafx.scene.control.TextField;
import javafx.scene.control.cell.PropertyValueFactory;
import model.Civil;
import model.SuperHeros;
import service.dao.UserDao;

public class FicheSHController implements Initializable{
	@FXML
	private Slider score;
	@FXML
	private TextField comm;
	@FXML
	private TextField ptfai;
	@FXML
	private TextField pouvoir;
	@FXML
	private TextField name;
	@FXML
	private TableView<FxCivil> tabciv;
	@FXML
	private TableColumn<FxCivil, String> colnom;
	@FXML
	private TableColumn<FxCivil, String> colprenom;
	@FXML
	private TextField nom;
	@FXML
	private TextField prenom;
	@FXML
	private Button btnfiltre;
	@FXML
	private Button btnfval;
	@FXML
	private Button btnann;
	@FXML
	private TextField civchoi;
	private SuperHeros SH;
	
	private int idvic=0;

	public int getIdvic() {
		return idvic;
	}
	public void setIdvic(int idvic) {
		this.idvic = idvic;
	}
	// Event Listener on Button[#btnfiltre].onAction
	@FXML
	public void btnfiltreh(ActionEvent event) {
		if (nom.getText().length()!=0 || prenom.getText().length()!=0) {
			ObservableList<FxCivil> dat =FXCollections.observableArrayList(remptb());
			tabciv.setItems(dat);
		}else {
			UserController user = new UserController();
			ObservableList<FxCivil> data = FXCollections.observableArrayList(user.findAllCivil());
			tabciv.setItems(data);
		}
	}
	public FicheSHController(SuperHeros SH) {
		this.SH=SH;
	}
	// Event Listener on Button[#btnfiltre1].onAction
	@FXML
	public void btnannh(ActionEvent event) {
		// TODO Autogenerated
		try {
			Parent page =(Parent) FXMLLoader.load(getClass().getResource("SuperHeros.fxml"));
			Scene scene4 = new Scene(page);
			Main.window.setScene(scene4);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		Main.window.setTitle("Super héros");
		Main.window.setWidth(910);
		Main.window.setHeight(650);
	}
	// Event Listener on Button[#btnfiltre11].onAction
	@FXML
	public void btnfvalh(ActionEvent event) {
		// TODO Autogenerated
		if (name.getText().length()==0 || pouvoir.getText().length()==0 || ptfai.getText().length()==0 || getIdvic()==0) {
			JOptionPane.showMessageDialog(null, "Remplissez tous les champs suivis d'* svp", "Erreur", JOptionPane.ERROR_MESSAGE);	
		}else {
			UserDao user = new UserDao();
			Connection conn = user.getConnection();
			Statement statement=null;
			boolean svex = false;
			String query2 ="SELECT * FROM supervilain WHERE IdCiv = "+idvic;
			try {
				statement = conn.createStatement();
				ResultSet res = statement.executeQuery(query2);
				if (res.next()) {
					svex=true;
				}
				
			} catch (SQLException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			if(svex==false) {
				if (SH!=null) {
					String query="UPDATE superheros SET nom ='"+name.getText()+"', pouvoir = '"+pouvoir.getText()+"', pointFaible = '"+ptfai.getText()+"', score = "+(int)score.getValue()+", IdCiv = "+idvic;
					if (comm.getText().length()!=0) {
						query+=", commentaire = '"+comm.getText()+"'";
					}
					query+=" WHERE idSH = "+SH.getIdSH();
					try {
						statement = conn.createStatement();
						statement.executeQuery(query);
						JOptionPane.showMessageDialog(null, "Modification réussie", "Changement", JOptionPane.INFORMATION_MESSAGE);
						try {
							Parent page =(Parent) FXMLLoader.load(getClass().getResource("SuperHeros.fxml"));
							Scene scene4 = new Scene(page);
							Main.window.setScene(scene4);
						} catch (IOException e) {
							// TODO Auto-generated catch block
							e.printStackTrace();
						}
						Main.window.setTitle("Super héros");
						Main.window.setWidth(910);
						Main.window.setHeight(650);
					} catch (SQLException e) {
						throw new RuntimeException(e);
					}
				}else {
					String query="";
					query = "SELECT * from superheros WHERE IdCiv ="+idvic;
					try {
						ResultSet result = statement.executeQuery(query);
						if (result.next()) {
							query = "UPDATE superheros SET nom = '"+name.getText()+"', pouvoir = '"+pouvoir.getText()+"',score ="+(int)score.getValue()+", pointFaible= '"+ptfai.getText()+"'";
							if (comm.getText().length()!=0) {
								query +=",commentaire = '"+comm.getText()+"'";
							} 
							query+=" WHERE IdCiv = "+idvic;
							statement.executeQuery(query);
							JOptionPane.showMessageDialog(null, "Changement réussi", "Changement", JOptionPane.INFORMATION_MESSAGE);
							try {
								Parent page =(Parent) FXMLLoader.load(getClass().getResource("SuperHeros.fxml"));
								Scene scene4 = new Scene(page);
								Main.window.setScene(scene4);
							} catch (IOException e) {
								// TODO Auto-generated catch block
								e.printStackTrace();
							}
							Main.window.setTitle("Super héros");
							Main.window.setWidth(910);
							Main.window.setHeight(650);
						}else {
							query = "INSERT INTO superheros (nom,pouvoir,score,pointFaible,IdCiv";
							if (comm.getText().length()!=0) {
								query +=",commentaire";
							}
							query+=") VALUES ('"+name.getText()+"','"+pouvoir.getText()+"',"+(int)score.getValue()+",'"+ptfai.getText()+"',"+idvic;
							if (comm.getText().length()!=0) {
								query +=",'"+comm.getText()+"'";
							}
							query+=")";
							try {
								statement.executeQuery(query);
								JOptionPane.showMessageDialog(null, "Ajout réussi", "Ajout", JOptionPane.INFORMATION_MESSAGE);
								try {
									Parent page =(Parent) FXMLLoader.load(getClass().getResource("SuperHeros.fxml"));
									Scene scene4 = new Scene(page);
									Main.window.setScene(scene4);
								} catch (IOException e) {
									// TODO Auto-generated catch block
									e.printStackTrace();
								}
								Main.window.setTitle("Super héros");
								Main.window.setWidth(910);
								Main.window.setHeight(650);
							} catch (SQLException e) {
								throw new RuntimeException(e);
							}
						}
					} catch (SQLException e) {
						throw new RuntimeException(e);
					}
				}	
			}else {
				JOptionPane.showMessageDialog(null, "Ajout impossible, un super vilain est déjà lié à ce civil!", "Erreur", JOptionPane.INFORMATION_MESSAGE);
				try {
					Parent page =(Parent) FXMLLoader.load(getClass().getResource("SuperHeros.fxml"));
					Scene scene4 = new Scene(page);
					Main.window.setScene(scene4);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
				Main.window.setTitle("Super héros");
				Main.window.setWidth(910);
				Main.window.setHeight(650);
			}
		}
	}

	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		UserController user = new UserController();
		ObservableList<FxCivil> data = FXCollections.observableArrayList(user.findAllCivil());
		tabciv.setEditable(true);
		colprenom.setCellValueFactory(new PropertyValueFactory<>("lastName"));
		colnom.setCellValueFactory(new PropertyValueFactory<>("firstName"));
		tabciv.setItems(data);
		tabciv.setOnMouseClicked( event -> {
			if( event.getClickCount() == 2 && tabciv.getSelectionModel().getSelectedItem()!=null) {
			  setIdvic(tabciv.getSelectionModel().getSelectedItem().getCivil().getId());
			  civchoi.setText(tabciv.getSelectionModel().getSelectedItem().getFirstName()+" "+tabciv.getSelectionModel().getSelectedItem().getLastName());
			}});
	}
	public ObservableList<FxCivil> remptb(){
		ArrayList<Civil> data = new ArrayList<Civil>();
		ObservableList<FxCivil> dat =FXCollections.observableArrayList();
		String query="";
		if (nom.getText().length()!=0 && prenom.getText().length()!=0) {
			query="select * from civil WHERE nom LIKE '%"+nom.getText()+"%' AND prenom LIKE '%"+prenom.getText()+"%'";
		}
		if (nom.getText().length()==0 && prenom.getText().length()!=0) {
			query="select * FROM civil WHERE prenom LIKE  '%"+prenom.getText()+"%'";
		}
		if (nom.getText().length()!=0 && prenom.getText().length()==0) {
			query="select * FROM civil WHERE nom LIKE  '%"+nom.getText()+"%'";
		}
		UserDao user = new UserDao();
		Connection conn = user.getConnection();
		Statement statement=null;
		try {
			statement = conn.createStatement();
			ResultSet result = statement.executeQuery(query);
			while(result.next()) {
				Civil civ = new Civil(result.getString("nom"),result.getString("prenom"),result.getString("civilite"),result.getString("coordonees"),result.getDate("dateNaissance").toLocalDate().atStartOfDay(ZoneOffset.UTC).toInstant(),result.getString("nationalite"),null,null,result.getDate("dateAjout").toLocalDate().atStartOfDay(ZoneOffset.UTC).toInstant(),null,null,result.getInt("IdCiv"));
				if (result.getDate("dateDeces")!=null) {
					civ.setDeathDate(result.getDate("dateDeces").toLocalDate().atStartOfDay(ZoneOffset.UTC).toInstant());
				}
				if (result.getString("Login")!=null) {
					civ.setLogin(result.getString("Login"));
				}
				if (result.getString("commentaire")!=null) {
					civ.setCommentaire(result.getString("commentaire"));
				}
				if (result.getDate("dateModification")!=null) {
					civ.setModifDate(result.getDate("dateModification").toLocalDate().atStartOfDay(ZoneOffset.UTC).toInstant());
				}
				data.add(civ);
			}
			for (Civil civ : data) {
				FxCivil fxciv = new FxCivil(civ);
				dat.add(fxciv);
			}
			return dat;
		} catch (SQLException e) {
			throw new RuntimeException(e);
		}
	}
	public void remplissage(SuperHeros SH) {
		name.setText(SH.getNom());
		pouvoir.setText(SH.getPouvoir());
		ptfai.setText(SH.getPointFaible());
		score.setValue((double)SH.getScore());
		if (SH.getCommentaire2()!=null) {
			comm.setText(SH.getCommentaire2());
		}
		idvic=SH.getId();
		UserDao user = new UserDao();
		Connection conn = user.getConnection();
		Statement statement=null;
		String query2="SELECT * FROM superheros WHERE IdSH = "+SH.getIdSH();
		try {
			statement = conn.createStatement();
			ResultSet result = statement.executeQuery(query2);
			if (result.next()) {
				setIdvic(result.getInt("IdCiv"));
				SH.setId(result.getInt("IdCiv"));
			}
		} catch (SQLException e) {
			throw new RuntimeException(e);
		}
		String query="SELECT * FROM civil WHERE IdCiv = "+SH.getId();
		try {
			statement = conn.createStatement();
			ResultSet result = statement.executeQuery(query);
			if (result.next()) {
				civchoi.setText(result.getString("nom")+" "+result.getString("prenom"));
			}
		} catch (SQLException e) {
			throw new RuntimeException(e);
		}
	}
}
