package ui;

import java.io.IOException;
import java.net.URL;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.ZoneOffset;
import java.util.ArrayList;
import java.util.ResourceBundle;

import javax.swing.JOptionPane;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TableView;
import javafx.scene.control.cell.PropertyValueFactory;
import model.SuperVilain;
import service.dao.UserDao;

public class SuperVilainsController implements Initializable{
	@FXML
	private TableView<FxSV> tabsh;
	@FXML
	private TableColumn<FxSV, String> colnom;
	@FXML
	private TableColumn<FxSV, String> colpouv;
	@FXML
	private TableColumn<FxSV, String> colptfai;
	@FXML
	private TableColumn<FxSV, String> colciv;
	@FXML
	private TableColumn<FxSV, Integer> coldegmal;
	@FXML
	private TableColumn<FxSV, String> colcomm;
	@FXML
	private Button btnsupp;
	@FXML
	private Button btnann;
	@FXML
	private Button btnajt;
	@FXML
	private Button btnraf;
	private ObservableList<FxSV> data = FXCollections.observableArrayList(findallfx());
	// Event Listener on Button[#btnsupp].onAction
	@FXML
	public void btnsupph(ActionEvent event) {
		// TODO Autogenerated
		if (tabsh.getSelectionModel().getSelectedItem()!=null) {
			FxSV FxSV = tabsh.getSelectionModel().getSelectedItem();
			SuperVilain SV = FxSV.getSuperVilain();
			String query = "DELETE FROM supervilain WHERE idSV="+SV.getIdSV();
			UserDao user = new UserDao();
			Connection conn = user.getConnection();
			Statement statement=null;
			try {
				statement = conn.createStatement();
				statement.executeQuery(query);
				JOptionPane.showMessageDialog(null, "Suppression réussie", "Information", JOptionPane.INFORMATION_MESSAGE);
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			raf();
		}
	}
	// Event Listener on Button[#btnann].onAction
	@FXML
	public void btnannh(ActionEvent event) {
		// TODO Autogenerated
		try {
			Parent page =(Parent) FXMLLoader.load(getClass().getResource("Menu.fxml"));
			Scene scene4 = new Scene(page);
			Main.window.setScene(scene4);
			Main.window.setTitle("Menu");
			Main.window.setWidth(600);
			Main.window.setHeight(340);
		} catch (IOException g) {
			// TODO Auto-generated catch block
			g.printStackTrace();
		}
	}
	// Event Listener on Button[#btnajt].onAction
	@FXML
	public void btnajth(ActionEvent event) {
		// TODO Autogenerated
		try {
		    FXMLLoader loader = new FXMLLoader(getClass().getResource("FicheSV.fxml"));
			FicheSVController fch = new FicheSVController(null);
			loader.setController(fch);
		 	Parent page = loader.load() ;
			Scene scene4 = new Scene(page);
			Main.window.setScene(scene4);
			Main.window.setTitle("Fiche super vilain");
			Main.window.setWidth(360);
			Main.window.setHeight(690);
		} catch (IOException g) {
			// TODO Auto-generated catch block
			g.printStackTrace();
		}
	}
	// Event Listener on Button[#btnraf].onAction
	@FXML
	public void btnrafh(ActionEvent event) {
		// TODO Autogenerated
		data.clear();
		data=FXCollections.observableArrayList(findallfx());
		tabsh.setItems(data);	
	}
	public ArrayList<FxSV> findallfx() {
		ArrayList<FxSV> list = new ArrayList<FxSV>();
		ArrayList<SuperVilain> liste = new ArrayList<SuperVilain>(findallSV());
		for (SuperVilain SV : liste) {
			FxSV fxSV = new FxSV(SV);
			UserDao user = new UserDao();
			Connection conn = user.getConnection();
			Statement statement=null;
			try {
				statement = conn.createStatement();
				String query="Select * FROM civil WHERE IdCiv = "+SV.getId();
				ResultSet rs = statement.executeQuery(query);
				if (rs.next()) {
					fxSV.setNomPreCiv(rs.getString("nom")+" "+rs.getString("prenom"));
				}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			list.add(fxSV);
		}
		return list;
	}
	public ArrayList<SuperVilain> findallSV(){
		ArrayList<SuperVilain> liste = new ArrayList<SuperVilain>();
		UserDao user = new UserDao();
		Connection conn = user.getConnection();
		Statement statement=null;
		try {
			statement = conn.createStatement();
			ResultSet result = statement.executeQuery("select * from supervilain");
			while(result.next()) {
				if (result.getInt("IdCiv")!=0) {
					ResultSet result2 = statement.executeQuery("select * from civil where IdCiv="+result.getInt("IdCiv"));
					result2.next();
					SuperVilain SV = new SuperVilain(result2.getString("nom"),result2.getString("prenom"),result2.getString("civilite"),result2.getString("coordonees"),result2.getDate("dateNaissance").toLocalDate().atStartOfDay(ZoneOffset.UTC).toInstant(),result2.getString("nationalite"),null,null,result2.getDate("dateAjout").toLocalDate().atStartOfDay(ZoneOffset.UTC).toInstant(),null,null,result.getInt("IdCiv"),result.getString("nom"),result.getString("pouvoir"),result.getString("pointFaible"),result.getString("commentaire"),result.getInt("degresMalveillance"),result.getInt("idSV"));
					if (result2.getDate("dateDeces")!=null) {
						SV.setDeathDate(result2.getDate("dateDeces").toLocalDate().atStartOfDay(ZoneOffset.UTC).toInstant());
					}
					if (result2.getString("commentaire")!=null) {
						SV.setCommentaire(result2.getString("commentaire"));
					}
					if (result2.getDate("dateModification")!=null) {
						SV.setModifDate(result2.getDate("dateModification").toLocalDate().atStartOfDay(ZoneOffset.UTC).toInstant());
					}
					if (result2.getString("Login")!=null) {
						SV.setLogin(result2.getString("Login"));
					}
					liste.add(SV);
				}else {
					SuperVilain SV = new SuperVilain(null,null,null,null,null,null,null,null,null,null,null,0,result.getString("nom"),result.getString("pouvoir"),result.getString("pointFaible"),result.getString("commentaire"),result.getInt("degresMalveillance"),result.getInt("idSV"));
					liste.add(SV);
				}
			}
			return liste;

		} catch (SQLException e) {
			throw new RuntimeException(e);
		}
	}
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		tabsh.setEditable(true);
		colnom.setCellValueFactory(new PropertyValueFactory<>("Nom"));
		colpouv.setCellValueFactory(new PropertyValueFactory<>("Pouvoir"));
		colptfai.setCellValueFactory(new PropertyValueFactory<>("PointFaible"));
		coldegmal.setCellValueFactory(new PropertyValueFactory<>("DegresMalveillance"));
		colcomm.setCellValueFactory(new PropertyValueFactory<>("Commentaire2"));
		colciv.setCellValueFactory(new PropertyValueFactory<>("NomPreCiv"));
		tabsh.setItems(data);
		tabsh.setOnMouseClicked( event -> {
			if( event.getClickCount() == 2 && tabsh.getSelectionModel().getSelectedItem()!=null) {
				SuperVilain SV = tabsh.getSelectionModel().getSelectedItem().getSuperVilain();
				 try {	
					 	FXMLLoader loader = new FXMLLoader(getClass().getResource("FicheSV.fxml"));
						FicheSVController fch = new FicheSVController(SV);
						loader.setController(fch);
					 	Parent page = loader.load() ;
						Scene scene4 = new Scene(page);
						Main.window.setScene(scene4);
						Main.window.setTitle("Fiche super vilain : "+SV.getNom());
						Main.window.setWidth(360);
						Main.window.setHeight(690);
						fch.remplissage(SV);
					} catch (IOException g) {
						// TODO Auto-generated catch block
						g.printStackTrace();
					}
			}});
	}
	public void raf() {
		// TODO Autogenerated
		data.clear();
		data=FXCollections.observableArrayList(findallfx());
		tabsh.setItems(data);	
	}
}
